CREATE DATABASE IF NOT EXISTS TIENDA;

USE TIENDA;

CREATE TABLE IF NOT EXISTS USUARIOS(
    ID_USUARIO  INT(11) AUTO_INCREMENT  NOT NULL,
    NOMBRES     VARCHAR(100)            NOT NULL,
    APELLIDOS   VARCHAR(100)            NOT NULL,
    EMAIL       VARCHAR(200)            NOT NULL,
    PASSWORD    VARCHAR(255)            NOT NULL,
    ROL         VARCHAR(20),
    IMAGEN      VARCHAR(255),
    CONSTRAINT  PK_USUARIO  PRIMARY KEY(ID_USUARIO)
    CONSTRAINT  UQ_IMAIL    UNIQUE(EMAIL)

)ENGINE=InnoDb; 

INSERT INTO USUARIOS VALUES(NULL, 'ADMIN', 'ADMIN', 'ADMIN@ADMIN.COM', '12345', 'ADMIM', 'IMAGEN');


